export const GET_HOT_PRODUCTS = 'GET_HOT_PRODUCTS'
export const CHANGE_STATE = 'CHANGE_STATE'
export const GET_PRODUCTS_DETAIL = "GET_PRODUCTS_DETAIL"
export const GET_PRODUCTS_FROM_MARKET = "GET_PRODUCTS_FROM_MARKET"
